services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DATASOURCE_PASSWORD:-root}
      MYSQL_DATABASE: ${DATASOURCE_USERNAME:-accounts_db}
      MYSQL_ROOT_HOST: "%"
    ports:
      - "${DB_PORT:-3306}:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./entregables/BaseDatos.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${DATASOURCE_PASSWORD:-root}"]
      timeout: 20s
      retries: 10
      interval: 10s
    networks:
      - accounts-app-network

  accounts-backend:
    build:
      context: ./backend/accounts-backend
      dockerfile: Dockerfile
    image: accounts-backend-${BACKEND_IMAGE_TAG:-1.0.0}
    container_name: accounts-backend
    env_file: .env
    ports:
      - "${SERVER_PORT:-8081}:8081"
    depends_on:
      mysql-db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/api/clientes"]
      interval: 30s
      timeout: 5s
      retries: 3
    networks:
      - accounts-app-network

#Frontend
  frontend:
    build:
      context: ./frontend/accounts-app-frontend
      dockerfile: Dockerfile
    image: accounts-frontend:${FRONTEND_VERSION:-latest}
    container_name: accounts-frontend
    ports:
      - "${FRONTEND_PORT}:80"
    depends_on:
      - accounts-backend
    networks:
      - accounts-app-network
    restart: unless-stopped


volumes:
  mysql-data:

networks:
  accounts-app-network:
    driver: bridge
  mysql-data:
    driver: local

